apiVersion: "monitoring.coreos.com/v1"
kind: PrometheusRule
metadata:
  labels:
    team: fyllut-sendinn
  name: innsending-api-alerts-dev
  namespace: fyllut-sendinn
spec:
  groups:
    - name: fyllut-sendinn-gcp-dev-alerts
      rules:
        - alert: archiving failed
          expr: sum(innsendingapi_archiving_of_applications_failed_total{namespace="team-soknad"}) > 0
          for: 1m
          annotations:
            consequence: "_*{{ $labels.container }}*_ has reported archiving of {{ $value }} application(s) have failed."
            action: "Check logs https://logs.adeo.no/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2h,to:now))&_a=(columns:!(message,envclass,level,application,host),filters:!(),index:'96e648c0-980a-11e9-830a-e17bbd64b4db',interval:auto,query:(language:lucene,query:'application:soknadsarkiverer%20AND%20cluster:dev-gcp%20AND%20level:Error'),sort:!(!('@timestamp',desc)))"
            documentation: "https://prometheus.io/docs/prometheus/latest/querying/basics/"
            summary: "Container _*{{ $labels.container }}*_ has reported archiving of {{ $value }} application(s) have failed."
            sla: "Action should be taken as soon as possible"
          labels:
            severity: critical
            namespace: fyllut-sendinn
            special_type_to_use_in_alertmanager_config: fyllut-sendinn-backend
        - alert: number of sent in
          expr: ceil(sum(increase(innsendingapi_number_of_operations_total{operation="OPPRETT"}[1d])) by (operation)) > 1500
          for: 1m
          annotations:
            consequence: "_*{{ $labels.container }}*_ has reported that the number of created applications {{ $value }} application(s) is above 1500."
            action: "Check logs https://logs.adeo.no/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1d,to:now))&_a=(columns:!(message,envclass,level,application,pod),filters:!(),index:'96e648c0-980a-11e9-830a-e17bbd64b4db',interval:auto,query:(language:lucene,query:'application:innsending-api%20AND%20cluster:prod-gcp%20AND%20(message:%22Opprettet%20s%C3%B8knad%22%20OR%20message:%22Opprettet%20ettersending%22%20OR%20message:%22Soknad%20fra%20fyllut%20persistert%22%20OR%20message:%22Skal%20opprette%20ettersendingssoknad%22)'),sort:!(!('@timestamp',desc)))"
            documentation: "https://prometheus.io/docs/prometheus/latest/querying/basics/"
            summary: "Container _*{{ $labels.container }}*_ has reported that the number of created applications {{ $value }} application(s) is above 1500."
            sla: "Check logs within 3h"
          labels:
            severity: warning
            special_type_to_use_in_alertmanager_config: fyllut-sendinn-backend
            namespace: fyllut-sendinn
            alert_type: custom
