name: Deploy alerts to gcp-dev
on:
  push:
    branches:
      - '*'
      - '!main'
    paths:
      - .github/workflows/dev-gcp.yml
jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy alertmanager config to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/fyllut-sendinn-slack-alertmanager.yml
          VARS: .nais/dev-config.json
