name: Deploy alerts to gcp-dev
on:
  push:
    branches:
      - '*'
      - '!main'
    paths:
      - .github/workflows/dev-gcp.yml
jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy alertmanager config to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/fyllut-sendinn-slack-alertmanager.yml
