name: Manually triggered deployment
run-name: Manual ${{ github.event.inputs.environment }} deploy of branch ${{ github.head_ref || github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'preprod'
        type: choice
        options:
          - none
          - preprod
          - prod

env:
  dev_channel: '#team-fyllut-sendinn-alerts-dev'
  prod_channel: '#team-fyllut-sendinn-alerts'
  resolved: 'true'

jobs:
  dev-deploy:
    if: github.event.inputs.environment == 'preprod'
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy alertmanager config to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/fyllut-sendinn-slack-alertmanager.yml
          VARS: .nais/dev-config.json

  prod-deploy:
    if: github.event.inputs.environment == 'prod'
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy alertmanager config to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/fyllut-sendinn-slack-alertmanager.yml
          VARS: .nais/prod-config.json
