name: Manually triggered deployment
run-name: Manual ${{ github.event.inputs.environment }} deploy of branch ${{ github.head_ref || github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'preprod'
        type: choice
        options:
          - none
          - preprod
          - prod

jobs:
  dev-deploy:
    if: github.event.inputs.environment == 'preprod'
    name: Deploy to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy alertmanager config to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/fyllut-sendinn-slack-alertmanager.yml
          VARS: .nais/dev-config.json

  prod-deploy:
    if: github.event.inputs.environment == 'prod'
    name: Deploy to prod
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy alertmanager config to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/fyllut-sendinn-slack-alertmanager.yml
