name: Deploy alerts to gcp-dev
on:
  push:
    branches:
      - '*'
      - 'main'
    paths:
      - .github/workflows/prod-gcp.yml
      - .nais/fyllut-sendinn-slack-altermanager.yml
jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy alertmanager config to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/fyllut-sendinn-slack-alertmanager.yml
          VARS: .nais/dev-config.json
