name: Deploy alerts to prod-gcp
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**/**.md'
jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy alertmanager config to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/fyllut-sendinn-slack-alertmanager.yml
